"""Candlestick encyclopedia doctrine for Candle Coach.

The encyclopedia is educational metadata, not detection logic and absolutely not
execution authority.  Pattern folklore is only useful after location,
participation, acceptance, and expectancy are checked.
"""

from __future__ import annotations

from typing import Any

CANDLE_ENCYCLOPEDIA_SCHEMA = "sharpedge.candle_encyclopedia.v1"


def _entry(
    name: str,
    family: str,
    window: str,
    bias: str,
    anatomy: str,
    auction_read: str,
    where_it_matters: str,
    confirmation: str,
    invalidation: str,
    false_positive: str,
) -> dict[str, str]:
    return {
        "name": name,
        "family": family,
        "window": window,
        "bias_hint": bias,
        "anatomy": anatomy,
        "auction_read": auction_read,
        "where_it_matters": where_it_matters,
        "confirmation": confirmation,
        "invalidation": invalidation,
        "false_positive": false_positive,
    }


CANDLE_ENCYCLOPEDIA: list[dict[str, str]] = [
    _entry(
        "Doji",
        "single / indecision",
        "1-candle",
        "neutral / compression",
        "Tiny real body; open and close nearly equal; wick mix can vary.",
        "Auction paused. Neither side owned the close.",
        "Most useful after an extended push, at VWAP, ORH/ORL, PDH/PDL, gamma walls, or prior swing levels.",
        "Break and hold beyond the doji high/low with participation and acceptance.",
        "Chop back through the body or low-volume boundary poke.",
        "In midday balance, tiny dojis are mostly noise confetti. Very decorative. Very useless.",
    ),
    _entry(
        "Dragonfly doji",
        "single / tail rejection",
        "1-candle",
        "bullish reversal attempt",
        "Tiny body near the high with a long lower wick and little/no upper wick.",
        "Sellers pushed lower but buyers reclaimed the close.",
        "Best at support, PDL/ORL/VWAP reclaim, LVN rejection, or downside exhaustion after a selloff.",
        "Next candle closes above the dragonfly high and retest holds above its midpoint/high.",
        "Lose the dragonfly low or fail immediately below VWAP/resistance.",
        "A long lower wick during a strong downtrend can be absorption before continuation, not magic demand fairy dust.",
    ),
    _entry(
        "Gravestone doji",
        "single / tail rejection",
        "1-candle",
        "bearish reversal attempt",
        "Tiny body near the low with a long upper wick and little/no lower wick.",
        "Buyers probed higher but sellers rejected the close.",
        "Best at resistance, PDH/ORH/VWAP rejection, call wall, or upside exhaustion after a squeeze.",
        "Next candle closes below the gravestone low and failed retest holds under its midpoint/low.",
        "Reclaim the gravestone high with acceptance and volume.",
        "In strong trend-up, this can be simple profit-taking before continuation.",
    ),
    _entry(
        "Spinning top",
        "single / indecision",
        "1-candle",
        "pause / balance",
        "Small body with meaningful upper and lower wicks.",
        "Both sides probed; neither side finished the auction with control.",
        "Useful as a pause marker after impulse or inside compression near a known reference.",
        "Expansion through either wick extreme with relative volume and acceptance.",
        "Repeated overlap around the body; no range expansion.",
        "Calling every spinning top a reversal is how accounts learn slapstick.",
    ),
    _entry(
        "Hammer / demand tail",
        "single / tail rejection",
        "1-candle",
        "bullish reversal attempt",
        "Small/medium body near the high; long lower wick, small upper wick.",
        "Lower prices were rejected; buyers defended into the close.",
        "Matters after a push down into support, VWAP reclaim, put wall, ORL failed breakdown, or gap-fill area.",
        "Close above the hammer high; better if pullback holds above the hammer body.",
        "Break below the tail low or reclaim fails at nearby overhead supply.",
        "A hammer in the middle of nowhere is just a candle wearing a cape.",
    ),
    _entry(
        "Hanging man",
        "single / distribution warning",
        "1-candle",
        "bearish warning after advance",
        "Hammer-like body after an up-push: long lower wick, small upper wick.",
        "Sellers finally forced a downside test; buyers recovered, but control is no longer clean.",
        "Most meaningful after extended upside into resistance, PDH/ORH, call wall, or upper expected-move band.",
        "Bearish case confirms on a close below the hanging-man low with failed reclaim.",
        "Acceptance above the high with trend participation.",
        "Without prior advance, it is not a hanging man. Context, butcher. Context.",
    ),
    _entry(
        "Inverted hammer",
        "single / reversal probe",
        "1-candle",
        "bullish reversal attempt after selloff",
        "Small body near the low/mid with long upper wick after decline.",
        "Buyers tested supply above; first probe failed, but demand showed up.",
        "Useful near support after downside momentum when the next candle can reclaim the wick.",
        "Next candle takes and holds the inverted-hammer high.",
        "Lose the low or fail under VWAP/resistance with weak volume.",
        "The pattern is early; without follow-through it is just rejected upside.",
    ),
    _entry(
        "Shooting star / supply tail",
        "single / tail rejection",
        "1-candle",
        "bearish reversal attempt",
        "Small body near the low with long upper wick after an up-push.",
        "Higher prices were rejected; sellers won the close.",
        "Matters into resistance, VWAP rejection, ORH/PDH failed breakout, call wall, or exhausted squeeze.",
        "Close below the star low; stronger if retest rejects the body/midpoint.",
        "Reclaim and accept above the star high.",
        "In a strong trend, stars can be pause candles before another leg up.",
    ),
    _entry(
        "Bullish/Bearish marubozu",
        "single / conviction",
        "1-candle",
        "continuation / control",
        "Large real body with very small wicks.",
        "One side controlled nearly the whole interval.",
        "Useful when it breaks a known level or initiates from VWAP/OR range with participation.",
        "Acceptance beyond the close and midpoint defense on retest.",
        "Immediate midpoint loss/reclaim against the candle direction.",
        "Late marubozu after a stretched move can mark exhaustion, not continuation.",
    ),
    _entry(
        "Strong bull/bear candle",
        "single / pressure",
        "1-candle",
        "directional pressure",
        "Body dominates more than half the range; wick balance is secondary.",
        "Close shows directional control for that bar.",
        "Useful only with relative volume, level interaction, and follow-through context.",
        "Next bar holds the midpoint or expands in the same direction.",
        "Fast fade through midpoint or failure at known level.",
        "One strong candle inside chop is a bullhorn in a closet.",
    ),
    _entry(
        "Bullish/Bearish engulfing",
        "two-candle / reversal",
        "2-candle",
        "reversal / reclaim attempt",
        "Second body fully swallows prior opposite-color body.",
        "Control flips from one side to the other across two bars.",
        "Best after a push into a major reference level, failed break, or exhaustion zone.",
        "Follow-through beyond the engulfing high/low plus retest acceptance.",
        "Price falls back inside the engulfed body and cannot reclaim direction.",
        "Engulfing in balanced chop often just means range expansion without edge.",
    ),
    _entry(
        "Piercing line",
        "two-candle / bullish reclaim",
        "2-candle",
        "bullish reversal attempt",
        "Green candle closes above midpoint of prior red body but below prior open.",
        "Sellers extended; buyers reclaimed more than half the prior auction.",
        "Best at support or after a failed breakdown where reclaim has participation.",
        "Acceptance above prior open; hold above midpoint on pullback.",
        "Reject prior midpoint/open and lose current low.",
        "Without downside context it is just partial recovery, not a setup.",
    ),
    _entry(
        "Dark cloud cover",
        "two-candle / bearish rejection",
        "2-candle",
        "bearish reversal attempt",
        "Red candle closes below midpoint of prior green body but above prior open.",
        "Buyers extended; sellers reclaimed more than half the prior auction.",
        "Best at resistance or after a failed breakout where rejection has participation.",
        "Acceptance below prior open; failed retest of midpoint/body.",
        "Reclaim prior midpoint/high with acceptance.",
        "In trend-up this can be a shallow pause before continuation.",
    ),
    _entry(
        "Harami / inside body",
        "two-candle / compression",
        "2-candle",
        "pause / compression",
        "Second body is contained inside prior body.",
        "Momentum pauses; the auction compresses inside the prior body.",
        "Useful near boundaries when compression defines a clean trigger box.",
        "Expansion out of the mother candle with participation and acceptance.",
        "Boundary poke that immediately returns inside the mother candle.",
        "Inside-body guessing is premium-donation behavior. Don’t be generous to market makers.",
    ),
    _entry(
        "Inside bar",
        "two-candle / compression",
        "2-candle",
        "direction unresolved",
        "Entire range sits inside the prior candle range.",
        "Volatility contracts; future expansion matters more than current direction.",
        "Best around OR/VWAP/major levels where both breakout and trap routes are visible.",
        "Breakout/breakdown holds beyond mother-bar range with volume.",
        "Failed break back inside range; treat as trap/fade candidate only if spine agrees.",
        "Inside bars are not bullish or bearish by themselves. They are loaded springs, not arrows.",
    ),
    _entry(
        "Outside bar",
        "two-candle / expansion",
        "2-candle",
        "volatility expansion",
        "Current high exceeds prior high and current low breaks prior low.",
        "Auction swept both sides; close location tells who won the expansion.",
        "Useful at failed breaks, liquidity sweeps, news candles, or volatility expansion windows.",
        "Direction requires close beyond one side and acceptance on retest.",
        "Close back near center with no follow-through; both sides got chopped.",
        "Outside bars during catalysts can be pure whipsaw. Respect event radar.",
    ),
    _entry(
        "Tweezer top/bottom",
        "two-candle / repeated test",
        "2-candle",
        "support/resistance test",
        "Two candles print nearly equal highs or lows.",
        "Auction retested the same level and failed to make fresh progress.",
        "Best at known reference levels, range edges, gamma walls, or prior swing extremes.",
        "Move away from the shared level with close beyond both candle bodies.",
        "Break and accept through the shared high/low.",
        "Equal highs/lows inside tight chop are normal noise, not sacred geometry.",
    ),
    _entry(
        "Morning star",
        "three-candle / bullish reversal",
        "3-candle",
        "bullish reversal attempt",
        "Strong red candle, small pause candle, then green reclaim through first candle midpoint.",
        "Sell pressure exhausts, pauses, then buyers reclaim control.",
        "Best after a selloff into support, ORL/PDL failed breakdown, VWAP reclaim, or put wall.",
        "Close above the third candle high; pullback holds above star/body midpoint.",
        "Lose the star low or reject below the first candle midpoint.",
        "Without prior decline, it is just three candles looking dramatic.",
    ),
    _entry(
        "Evening star",
        "three-candle / bearish reversal",
        "3-candle",
        "bearish reversal attempt",
        "Strong green candle, small pause candle, then red rejection through first candle midpoint.",
        "Buy pressure exhausts, pauses, then sellers reclaim control.",
        "Best after an up-push into resistance, ORH/PDH failed breakout, VWAP rejection, or call wall.",
        "Close below the third candle low; failed retest holds under the star/body midpoint.",
        "Reclaim above the star high or first candle midpoint with acceptance.",
        "Without prior advance, it is not an evening star. It’s just astrology with OHLC.",
    ),
    _entry(
        "Three white soldiers",
        "three-candle / continuation",
        "3-candle",
        "bullish continuation / squeeze risk",
        "Three strong green candles with rising closes.",
        "Buyers walk price higher bar by bar.",
        "Most useful after base breakout, VWAP reclaim, or trend day confirmation.",
        "Fourth/pullback bar holds above sequence midpoint and volume stays constructive.",
        "Fast fade of the third candle or loss of second candle midpoint.",
        "Late sequence can mean exhaustion. Great soldiers sometimes march off cliffs.",
    ),
    _entry(
        "Three black crows",
        "three-candle / continuation",
        "3-candle",
        "bearish continuation / liquidation risk",
        "Three strong red candles with falling closes.",
        "Sellers walk price lower bar by bar.",
        "Most useful after support break, VWAP rejection, or trend-down confirmation.",
        "Bounce fails below sequence midpoint and sellers hold lower highs.",
        "Reclaim of second/third candle midpoint with participation.",
        "Late crows after a big dump can be capitulation/exhaustion instead of fresh edge.",
    ),
    _entry(
        "Three inside up/down",
        "three-candle / inside breakout",
        "3-candle",
        "reversal / expansion attempt",
        "Large candle, inside/reclaim candle, then break beyond the first candle extreme.",
        "Compression inside the mother candle resolves through one boundary.",
        "Best when the mother candle tags a meaningful level and breakout aligns with acceptance.",
        "Hold beyond the mother candle high/low with retest support/resistance.",
        "Return inside the mother candle; trap risk takes over.",
        "A break without participation is just a boundary poke wearing a fake mustache.",
    ),
    _entry(
        "Three outside up/down",
        "three-candle / engulfing continuation",
        "3-candle",
        "reversal follow-through",
        "Engulfing pair followed by third candle closing beyond the engulfing direction.",
        "Control flips, then proves follow-through on the next bar.",
        "Best at major references after failed break/exhaustion, not in random mid-range chop.",
        "Third candle extreme holds on retest; midpoint of engulfing body remains defended.",
        "Third candle fully fades or price re-enters engulfed body.",
        "If the third candle is climactic into a wall, continuation can turn into exhaustion.",
    ),
    _entry(
        "Kicker",
        "two-candle / regime shock",
        "2-candle",
        "aggressive reversal / repricing",
        "Opposite-color candle opens/gaps away from prior body and drives strongly the other way.",
        "New information reprices the auction; prior side is trapped.",
        "Most meaningful around news, event radar catalysts, open drive, or hard level rejection.",
        "No immediate gap fill; acceptance holds beyond the kicker body.",
        "Fast fill back into prior candle body.",
        "On 1m data, micro gaps can be feed artifacts. Verify source and spread.",
    ),
    _entry(
        "Rising/Falling three methods",
        "five-candle / continuation",
        "5-candle",
        "trend continuation after pause",
        "Large impulse candle, three small countertrend candles contained inside it, then continuation candle.",
        "Trend pauses without surrendering the impulse range, then resumes.",
        "Best in trend day context with pullback holding VWAP/impulse midpoint.",
        "Continuation candle closes beyond impulse extreme with participation.",
        "Countertrend candles break the impulse candle low/high or VWAP fails.",
        "If the pause candles have heavy opposing volume, it may be distribution/absorption, not healthy rest.",
    ),
    _entry(
        "Abandoned baby",
        "three-candle / gap reversal",
        "3-candle",
        "rare reversal warning",
        "Strong candle, isolated doji gap, then opposite strong candle leaving the doji abandoned.",
        "Auction overextended, paused in isolation, then repriced opposite.",
        "More relevant on daily/session charts than noisy 1m SPY feed.",
        "Opposite candle holds and the gap/island is not reclaimed.",
        "Price fills back through the doji island.",
        "Rare on intraday liquid ETFs; don’t hallucinate it from tiny micro-gaps.",
    ),
]


def pattern_names() -> list[str]:
    """Return encyclopedia names in display order."""
    return [entry["name"] for entry in CANDLE_ENCYCLOPEDIA]


def encyclopedia_by_name() -> dict[str, dict[str, str]]:
    """Return normalized lookup keyed by exact pattern name."""
    return {entry["name"]: dict(entry) for entry in CANDLE_ENCYCLOPEDIA}


def encyclopedia_packet() -> dict[str, Any]:
    """Return a serializable Candle Coach encyclopedia packet."""
    return {
        "schema": CANDLE_ENCYCLOPEDIA_SCHEMA,
        "authority": "education_only_not_trade_permission",
        "entry_count": len(CANDLE_ENCYCLOPEDIA),
        "doctrine": (
            "Candlestick names describe auction events. Tradeability still requires "
            "location, participation/order flow, acceptance, and positive expectancy."
        ),
        "entries": [dict(entry) for entry in CANDLE_ENCYCLOPEDIA],
    }


__all__ = [
    "CANDLE_ENCYCLOPEDIA",
    "CANDLE_ENCYCLOPEDIA_SCHEMA",
    "encyclopedia_by_name",
    "encyclopedia_packet",
    "pattern_names",
]
